# Generated by Django 3.2 on 2021-04-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
