# Generated by Django 3.2 on 2021-04-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoblog', '0004_auto_20210427_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
